Resources:
  ElasticacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: "Elasticache Subnet Group Name"
      SubnetIds:
        Fn::Split:
          - ","
          - Fn::ImportValue: 
              Ref: ServiceSubnetIds

  ElasticacheSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Elasticache Security Group"
      VpcId: 
        Fn::ImportValue: 
          Ref: VpcId
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: "6379"
          ToPort: "6379"
          SourceSecurityGroupId:
            Fn::ImportValue: 
              Ref: ServiceSecurityGroup

  ElasticacheCluster:
    Type: "AWS::ElastiCache::CacheCluster"
    Properties:
      AZMode: "cross-az"
      CacheNodeType: "cache.m3.medium"
      Engine: "redis"
      NumCacheNodes: "1"
      CacheSubnetGroupName: 
        Ref: ElasticacheSubnetGroup
      VpcSecurityGroupIds:
        - Fn::ImportValue: 
            Ref: ServiceSecurityGroup
